CREATE TABLE customer_location (
  CustomerID VARCHAR(50),
  ZipCode NUMBER(5),
  City VARCHAR(50),
  State VARCHAR(2),
  OrderID VARCHAR(50),
  PurchaseTimeStamp DATE,
  Price NUMBER(9,2)
);

CREATE TABLE product_category (
  OrderID VARCHAR(50),
  ProductID VARCHAR(50),
  ProductCategory VARCHAR(50),
  Price NUMBER(9,2),
  PurchaseTimeStamp DATE
);

CREATE TABLE seller_state (
  OrderID VARCHAR(50),
  SellerID VARCHAR(50),
  SellerState VARCHAR(2),
  CustomerID VARCHAR(50),
  CustomerState VARCHAR(2),
   Price NUMBER(9,2)
);

INSERT INTO customer_location
SELECT CUSTOMERID, CustomerZipCode, CITY, STATE, ORDERID, PurchaseTimeStamp, PRICE
FROM
(
    SELECT A.ORDERID, A.CUSTOMERID, PurchaseTimeStamp, PRICE, B.CustomerZipCode, C.CITY, C.STATE
    FROM ORDERS_DW A
    LEFT JOIN
    (
        SELECT CUSTOMERID, CustomerZipCode
        FROM CUSTOMERS_DW
    )B
    ON A.CUSTOMERID = B.CUSTOMERID
    LEFT JOIN
    (
        SELECT ZIPCODE, CITY, STATE
        FROM ENTITY_DW
    )C
    ON B.CustomerZipCode = C.ZIPCODE
);

COMMIT;

INSERT INTO product_category
SELECT A.ORDERID, B.PRODUCTID, C.PRODUCTCATEGORY, A.PRICE, A.PurchaseTimeStamp
FROM ORDERS_DW A
LEFT JOIN
(
    SELECT ORDERID, PRODUCTID
    FROM ORDERITEMS_DW
)B
ON A.ORDERID = B.ORDERID
LEFT JOIN
(
    SELECT PRODUCTID, PRODUCTCATEGORY
    FROM PRODUCTS_DW
)C
ON B.PRODUCTID = C.PRODUCTID;

COMMIT;

INSERT INTO seller_state
SELECT A.ORDERID, B.SELLERID, D.STATE AS SELLERSTATE, A.CUSTOMERID, F.STATE AS CUSTOMERSTATE, A.PRICE
FROM ORDERS_DW A
LEFT JOIN
(
SELECT ORDERID, SELLERID
FROM ORDERITEMS_DW
)B
ON A.ORDERID = B.ORDERID
LEFT JOIN
(
SELECT SELLERID, SELLERZIPCODE
FROM SELLERS_DW
)C
ON B.SELLERID = C.SELLERID
LEFT JOIN
(
SELECT ZIPCODE, STATE
FROM ENTITY_DW
)D
ON C.SELLERZIPCODE = D.ZIPCODE
LEFT JOIN
(
SELECT CUSTOMERID, CUSTOMERZIPCODE
FROM CUSTOMERS_DW
)E
ON A.CUSTOMERID = E.CUSTOMERID
LEFT JOIN
(
SELECT ZIPCODE, STATE
FROM ENTITY_DW
)F
ON E.CUSTOMERZIPCODE = F.ZIPCODE;

COMMIT;